### 3. 파이토치 기초

In [1]:
import torch

def print_val(x):
    print "Type:", type(x)
    print "Shape:", x.shape
    print "값:\n", x
    print " "

In [2]:
x = torch.rand(2,3,2)
print_val(x)

x = torch.randn(2,3)
print_val(x)

Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3, 2])
값:
tensor([[[0.8116, 0.6675],
         [0.6676, 0.2857],
         [0.0927, 0.5112]],

        [[0.6910, 0.6184],
         [0.1310, 0.0754],
         [0.3937, 0.2680]]])
 
Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
값:
tensor([[ 0.6042,  0.0526,  0.3709],
        [-2.4780,  0.7886, -0.7422]])
 


In [3]:
x = torch.randperm(4)
print_val(x)

Type: <class 'torch.Tensor'>
Shape: torch.Size([4])
값:
tensor([3, 0, 2, 1])
 


In [4]:
x = torch.arange(0, 3, step=0.5)
print_val(x)

Type: <class 'torch.Tensor'>
Shape: torch.Size([6])
값:
tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])
 


In [5]:
print_val(torch.ones(3,4))
print_val(torch.zeros(3,4))

Type: <class 'torch.Tensor'>
Shape: torch.Size([3, 4])
값:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
 
Type: <class 'torch.Tensor'>
Shape: torch.Size([3, 4])
값:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
 


In [6]:
print_val(torch.Tensor(2,4))

Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 4])
값:
tensor([[-1.5439e-01,  3.0746e-41, -1.5439e-01,  3.0746e-41],
        [-1.5439e-01,  3.0746e-41, -1.5439e-01,  3.0746e-41]])
 


In [7]:
print_val(torch.Tensor([2,3]))
print_val(torch.Tensor([[2,3], [3,4]]))

Type: <class 'torch.Tensor'>
Shape: torch.Size([2])
값:
tensor([2., 3.])
 
Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 2])
값:
tensor([[2., 3.],
        [3., 4.]])
 


In [8]:
x = torch.FloatTensor(2,3)
print_val(x)

x = x.type_as(torch.IntTensor())
print_val(x)

Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
값:
tensor([[2.1898e+05, 4.5839e-41, 2.1898e+05],
        [4.5839e-41, 1.1774e-02, 4.5839e-41]])
 
Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
값:
tensor([[218976,      0, 218976],
        [     0,      0,      0]], dtype=torch.int32)
 


In [9]:
torch.FloatTensor(3,4,5).size()

torch.Size([3, 4, 5])

In [10]:
import numpy as np
np_x = np.ndarray((2,3), dtype=int)
print_val(np_x)

x = torch.from_numpy(np_x)
print_val(x)

Type: <type 'numpy.ndarray'>
Shape: (2, 3)
값:
[[140497981509456 140497981509520 140497981509584]
 [140497981096016 140498179808528 140498179808624]]
 
Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
값:
tensor([[140497981509456, 140497981509520, 140497981509584],
        [140497981096016, 140498179808528, 140498179808624]])
 
